### ISSUE TITLE
librabbitmq-devel-0.3.0  core down

### ISSUE THREAD

**Issue by hupantingxue** [rabbitmq/rabbitmq-c#13]
The call stack is:
#0  0x000000321fe328a5 in raise () from /lib64/libc.so.6
#1  0x000000321fe34085 in abort () from /lib64/libc.so.6
#2  0x000000321fe707b7 in __libc_message () from /lib64/libc.so.6
#3  0x000000321fe760e6 in malloc_printerr () from /lib64/libc.so.6
#4  0x000000321fe7656d in malloc_consolidate () from /lib64/libc.so.6
#5  0x000000321fe79385 in _int_malloc () from /lib64/libc.so.6
#6  0x000000321fe7a911 in malloc () from /lib64/libc.so.6
#7  0x00007f0ee34718f7 in amqp_tune_connection () from /usr/lib64/librabbitmq.so.1
#8  0x00007f0ee34719a7 in amqp_new_connection () from /usr/lib64/librabbitmq.so.1
#9  0x00000000004f18de in AMQP::sockConnect (this=0x7f0ea80008c0) at .../src/amqpcpp/src/AMQP.cpp:193
#10 0x00000000004f17a8 in AMQP::connect (this=0x7f0ea80008c0) at .../src/amqpcpp/src/AMQP.cpp:176
#11 0x00000000004f08fb in AMQP::AMQP (this=0x7f0ea80008c0, cnnStr=

```
"\230\020\v\001\000\000\000\000\225\221I\000\000\000\000\000?\177\321\016\177\000\000\210V\v\001\000\000\000\000\220\254\177\321\016\177\000\000\000\001\000\000\000\000\000\000h>\v\001\000\000\000\000\230\020\v\001\000\000\000\000\360\254\177\321\016\177\000\000\002\005N\000\000\000\000\000\360\254\177\321\016\177\000\000\372+N\000\000\000\000\000\230\020\v\001\000\000\000\000\000U\v\001\000\000\000\000\210V\v\001\000\000\000\000\001\vN\000\000\000\000\000@KL\000\000\000\000\000\000U\v\001\000\000\000\000\000\001\000\000\000\000\000\000h>\v\001\000\000\000\000\240\255\177\321\016\177\000\000w\006N\000\000\000\000\000(L\v\001\000\000\000\000h>\v\001\000\000\000\000\230\020\v\001", '\000' <repeats 21 times>, "U\v\001", '\000' <repeats 35 times>)
at .../src/amqpcpp/src/AMQP.cpp:26
```

**Comment by alanxz** [comment]
Do you have the same issue if you use rabbitmq-c v0.4.1?

Also this might be caused by [AMQPcpp](https://github.com/akalend/amqpcpp)

**Comment by lukebakken** [comment]
Please ask here:

https://github.com/alanxz/rabbitmq-c
