### ISSUE TITLE
Giving priority to consumers

### ISSUE THREAD

**Issue by Emreiris** [rabbitmq/rabbitmq-c#25]
Hello, I want to put a backup consumer to the main consumer to cover the case the main consumer goes down. I have given priority as
`  amqp_table_t args;
#if 1
  amqp_table_entry_t entry = {
      .key = amqp_cstring_bytes("x-priority"),
      .value = {.kind = AMQP_FIELD_KIND_I32, .value = m_priority}};

  args.entries = &entry;
  args.num_entries = 1;
#endif

  amqp_basic_consume(conn, 1, queuename, amqp_empty_bytes, 0, 1, 0,
                     amqp_empty_table);`
m_priority is a number between 1 and 10. But It seems no effect on consuming messages from the queue. How can I give priority to consumers?

**Comment by lukebakken** [comment]
Please ask in the official repo:

https://github.com/rabbitmq/rabbitmq-c/issues/10

https://github.com/alanxz/rabbitmq-c
