### ISSUE TITLE
cmake-based build should be preferred on Windows

### ISSUE THREAD

**Issue by dpw** [rabbitmq/rabbitmq-c#4]
Someone at the London real-time hackathon tried to use RabbitMQ and the C client, and was not able to get the C client to build.  I wasn't present, so I'm not sure exactly what the problem was.  But I think the fact that README.windows still emphasizes the mignw-based build is part of the problem.  The cmake-based build is probably the most acceptable to Windows developers at this point, so should be the emphasis in that file.  In fact, maybe mention of the other builds should be dropped entirely?

**Comment by majek** [comment]
The confused person is https://twitter.com/boggisre , initially tried using `amqcpp`. Later I pointed to rabbitmq-c, together we reviewed the readme and noticed that mingw might be required.

**Comment by alanxz** [comment]
I added a note in the README.windows file which should hopefully help with this kind of issue.

See: alanxz/rabbitmq-c@f89df37
