### ISSUE TITLE
amqp_basic_publish sends uninitialized 16 bits

### ISSUE THREAD

**Issue by MattiL** [rabbitmq/rabbitmq-c#9]
amqp_basic_publish sends uninitialized 16 bits because it does not initialize the ticket field of amqp_basic_publish_t before calling amqp_send_method with amqp_basic_publish_t m. The 16 bits come from stack.

**Comment by tonyg** [comment]
Good catch! I think you're right. The fix should be simple: add "m.ticket = 0;".

**Comment by alanxz** [comment]
Fix applied, see alanxz/rabbitmq-c@54024fe

Thanks for reporting it!

Note: the official sources have moved, if you have any further issues, please submit them in the [alanxz/rabbitmq-c](https://github.com/alanxz/rabbitmq-c) issue tracker
